{% set name = "napari-ism" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-ISM-{{ version }}.tar.gz
  sha256: 0c179c4ae9ed83de8366d3dfe87cd837610269981d34e4e2221b7d1bea0043c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - brighteyes-ism
    - h5py
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - scikit-image
    - scipy

test:
  imports:
    - napari_ism
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VicidominiLab/napari-ISM
  summary: It performs Adaptive Pixel Reassignment.
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
