{% set name = "napari-ism" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-ISM-{{ version }}.tar.gz
  sha256: cb03d28cc1f4fc1b41e313d6d8edda708b2595c6ce1e755741e3c4a7147f111b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - brighteyes-ism >=1.2.0
    - h5py
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - scikit-image
    - scipy

test:
  imports:
    - napari_ism
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VicidominiLab/napari-ISM
  summary: It performs Adaptive Pixel Reassignment.
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
