{% set name = "napari-ism" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06a8d667315a8dd34e2059130024ba96e8633203b8ee955348997fc726333aa6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - h5py
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - scikit-image
    - scipy

test:
  imports:
    - napari_ism
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VicidominiLab/napari-ISM
  summary: It performs Adaptive Pixel Reassignment.
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
